import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#F5F8E8",
    borderRadius: 20,
    width: "85%",
    maxWidth: 300,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalHeader: {
    marginBottom: 20,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#8B6F47",
    fontFamily: "KiwiMaru_400Regular",
  },
  imagePreviewContainer: {
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  imagePreview: {
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 2,
    borderColor: "#8B6F47",
  },
  optionContainer: {
    marginBottom: 20,
  },
  optionButton: {
    flexDirection: "column",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 12,
    marginBottom: 12,
    backgroundColor: "#FFFEF7",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#D4C5A0",
  },
  optionText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#8B6F47",
    marginTop: 8,
    fontFamily: "KiwiMaru_400Regular",
  },
  buttonContainer: {
    flexDirection: "row",
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#D4C5A0",
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  cancelButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
    fontFamily: "KiwiMaru_400Regular",
  },
  saveButton: {
    flex: 1,
    backgroundColor: "#8B6F47",
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  saveButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "white",
    fontFamily: "KiwiMaru_400Regular",
  },
});
