import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 12,
        paddingTop: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#E8E8E8",
    },
    headerTitle: {
        flex: 1,
        textAlign: "center",
        fontSize: 18,
        fontWeight: "600",
        color: "#333",
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
        paddingVertical: 20,
    },
    avatarSection: {
        alignItems: "center",
        marginBottom: 24,
        marginTop: 20,
    },
    avatarContainer: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: "#E8E8E8",
        justifyContent: "center",
        alignItems: "center",
    },
    profileInfo: {
        backgroundColor: "#F8F8F8",
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
    },
    userName: {
        fontSize: 20,
        fontWeight: "700",
        color: "#333",
        marginBottom: 4,
    },
    userId: {
        fontSize: 14,
        color: "#666",
        marginBottom: 12,
    },
    infoItem: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 10,
    },
    infoText: {
        fontSize: 13,
        color: "#666",
        marginLeft: 8,
    },
    bioSection: {
        marginBottom: 24,
    },
    bioLabel: {
        fontSize: 13,
        fontWeight: "600",
        color: "#666",
        marginBottom: 8,
    },
    bioBox: {
        backgroundColor: "white",
        borderWidth: 1,
        borderColor: "#E8E8E8",
        borderRadius: 8,
        padding: 12,
        minHeight: 80,
        justifyContent: "flex-start",
    },
    bioText: {
        fontSize: 14,
        color: "#666",
        lineHeight: 20,
    },
    statsContainer: {
        flexDirection: "row",
        gap: 12,
        marginBottom: 30,
    },
    statBox: {
        flex: 1,
        backgroundColor: "white",
        borderWidth: 1,
        borderColor: "#F0F0F0",
        borderRadius: 12,
        paddingVertical: 20,
        paddingHorizontal: 16,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    statLabel: {
        fontSize: 13,
        color: "#999",
        marginBottom: 10,
        fontWeight: "500",
    },
    statValue: {
        fontSize: 28,
        fontWeight: "700",
        color: "#4CAF50",
    },
});
