import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  topHeader: {
    marginBottom: 8,
    marginTop: 0,
  },
  content: {
    flexGrow: 1,
    paddingTop: 10,
    paddingBottom: 32,
    paddingHorizontal: 18,
    alignItems: "center",
  },
  cloud: {
    position: "absolute",
    backgroundColor: "#F6FBFF",
    borderRadius: 999,
    shadowColor: "#C9E2F7",
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
    opacity: 0.9,
  },
  cloudRight: {
    width: 120,
    height: 44,
    top: 24,
    right: 8,
  },
  cloudLeft: {
    width: 86,
    height: 32,
    top: 86,
    left: 24,
  },
  backTitle: {
    alignSelf: "flex-start",
    paddingTop: 6,
  },
  bannerWrapper: {
    marginTop: 18,
  },
  nameplate: {
    width: 220,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
  },
  nameplateText: {
    fontSize: 20,
    fontWeight: "700",
    color: "#6C4A2C",
    letterSpacing: 3,
  },
  leafWrapper: {
    marginTop: 12,
    marginBottom: 16,
    alignItems: "center",
  },
  leafImage: {
    width: 170,
    height: 150,
    resizeMode: "contain",
    transform: [{ rotate: "-6deg" }],
  },
  card: {
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#E3CBA5",
    shadowColor: "#B89B68",
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  fieldRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#D5B78E",
    borderStyle: "dashed",
  },
  fieldRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 6,
    alignItems: "flex-start",
  },
  iconBadge: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  iconImage: {
    width: 20,
    height: 20,
    resizeMode: "contain",
  },
  iconBadgeTop: {
    alignSelf: "flex-start",
    marginTop: 6,
  },
  fieldContent: {
    flex: 1,
    marginHorizontal: 10,
  },
  fieldPlaceholder: {
    fontSize: 16,
    color: "#B5906E",
    letterSpacing: 0.5,
  },
  fieldInput: {
    flex: 1,
    marginHorizontal: 10,
    fontSize: 16,
    color: "#7A4B2A",
    paddingVertical: 2,
    backgroundColor: "transparent",
  },
  memoField: {
    flex: 1,
    width: "100%",
    position: "relative",
    marginHorizontal: 10,
  },
  memoInput: {
    minHeight: 80,
    borderWidth: 1,
    borderColor: "#D5B78E",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 6,
    paddingRight: 36,
    marginHorizontal: 0,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
  },
  memoIconButton: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
  },
  actionButton: {
    width: 28,
    height: 28,
    borderRadius: 9,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  actionButtonTop: {
    alignSelf: "flex-start",
    marginTop: 6,
  },
  submitButton: {
    marginTop: 26,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  modalContent: {
    width: "100%",
    maxWidth: 360,
    maxHeight: "70%",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "#E3CBA5",
    shadowColor: "#B89B68",
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#6C4A2C",
    textAlign: "center",
    marginBottom: 10,
  },
  modalList: {
    maxHeight: 280,
  },
  modalItem: {
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E6D3B3",
  },
  modalItemText: {
    fontSize: 16,
    color: "#7A4B2A",
  },
  modalEmpty: {
    textAlign: "center",
    color: "#B5906E",
    paddingVertical: 18,
  },
  modalFooter: {
    marginTop: 12,
    alignItems: "center",
  },
  modalCloseButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#F0E3CF",
  },
  modalCloseText: {
    color: "#7A4B2A",
    fontWeight: "600",
  },
});
