import { FONT_FAMILY } from "@/config/fontConfig";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: 24,
    alignItems: "center",
  },
  headerRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
    paddingHorizontal: 4,
  },
  backTitle: {
    alignSelf: "flex-start",
    paddingTop: 6,
    paddingBottom: 4,
  },
  deleteButton: {
    padding: 8,
  },
  nameplateWrapper: {
    marginTop: 12,
    alignItems: "center",
  },
  nameplate: {
    width: 230,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
  },
  nameplateText: {
    fontSize: 22,
    fontWeight: "700",
    color: "#6C4A2C",
    letterSpacing: 1,
    fontFamily: FONT_FAMILY.regular,
  },
  treeVisualWrapper: {
    width: "90%",
    maxWidth: 300,
    aspectRatio: 1,
    marginTop: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  treeVisual: {
    width: "100%",
    height: "100%",
  },
  detailCard: {
    marginTop: 2,
    width: "90%",
    maxWidth: 340,
    alignSelf: "center",
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#E3CBA5",
    shadowColor: "#D9C2A3",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#D7B88E",
    borderStyle: "dashed",
  },
  iconBadge: {
    width: 26,
    height: 26,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  iconImage: {
    width: 18,
    height: 18,
    resizeMode: "contain",
  },
  detailText: {
    marginLeft: 10,
    fontSize: 16,
    color: "#7A4B2A",
    fontWeight: "600",
    fontFamily: FONT_FAMILY.medium,
  },
  memberTags: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    marginLeft: 10,
  },
  memberTag: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    backgroundColor: "#FFF8EC",
    borderWidth: 1,
    borderColor: "#D7B88E",
    marginRight: 6,
    marginBottom: 6,
  },
  memberTagText: {
    fontSize: 13,
    color: "#7A4B2A",
    fontFamily: FONT_FAMILY.regular,
  },
  dashLine: {
    flex: 1,
    marginLeft: 10,
    height: 1,
    borderBottomWidth: 1,
    borderBottomColor: "#B79066",
    borderStyle: "dashed",
  },
  leafListButton: {
    marginTop: 18,
  },
});
