import { FONT_FAMILY } from "@/config/fontConfig";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    topHeader: {
        marginBottom: 8,
        marginTop: 0,
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
        paddingVertical: 20,
    },
    avatarSection: {
        alignItems: "center",
        marginBottom: 24,
        marginTop: 20,
    },
    avatarContainer: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: "#FFFFFF",
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    avatarImage: {
        width: 100,
        height: 100,
        borderRadius: 50,
    },
    profileInfo: {
        backgroundColor: "#F5F8E8",
        borderRadius: 20,
        paddingVertical: 20,
        paddingHorizontal: 24,
        marginBottom: 20,
    },
    userName: {
        fontSize: 24,
        color: "#8B6F47",
        marginBottom: 2,
        textAlign: "center",
        fontFamily: FONT_FAMILY.medium,
    },
    userId: {
        fontSize: 16,
        color: "#8B6F47",
        marginBottom: 16,
        textAlign: "center",
        fontFamily: FONT_FAMILY.light,
    },
    divider: {
        borderTopWidth: 2,
        borderTopColor: "#8B6F47",
        borderStyle: "dashed",
        marginBottom: 16,
    },
    infoItem: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 14,
        paddingHorizontal: 8,
    },
    infoText: {
        fontSize: 14,
        color: "#8B6F47",
        marginLeft: 12,
        fontFamily: FONT_FAMILY.medium,
    },
    bioSection: {
        marginTop: 16,
    },
    bioLabel: {
        fontSize: 13,
        color: "#8B6F47",
        marginBottom: 8,
        fontFamily: FONT_FAMILY.light,
    },
    bioBox: {
        backgroundColor: "#FFFEF7",
        borderWidth: 1,
        borderColor: "#D4C5A0",
        borderRadius: 8,
        padding: 12,
        minHeight: 60,
        justifyContent: "flex-start",
    },
    bioText: {
        fontSize: 14,
        color: "#8B6F47",
        lineHeight: 20,
        fontFamily: FONT_FAMILY.light,
    },
    statsContainer: {
        flexDirection: "row",
        gap: 16,
        marginBottom: 30,
        justifyContent: "space-between",
        paddingHorizontal: 8,
    },
    statBoxWrapper: {
        flex: 1,
        position: "relative",
        minHeight: 140,
        borderRadius: 16,
        overflow: "hidden",
    },
    statBoxBackground: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: "100%",
        height: "100%",
        borderRadius: 16,
        resizeMode: "contain",
    },
    statBox: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1,
        paddingVertical: 24,
        paddingHorizontal: 16,
    },
    statLabel: {
        fontSize: 15,
        color: "#8B6F47",
        textAlign: "center",
        fontFamily: FONT_FAMILY.medium,
    },
    statValue: {
        fontSize: 36,
        fontWeight: "700",
        color: "#5D4E37",
        fontFamily: FONT_FAMILY.regular,
    },
});
