import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backTitle: {
    paddingTop: 6,
    marginBottom: 8,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  avatarSection: {
    alignItems: "center",
    marginBottom: 24,
    marginTop: 20,
  },
  avatarContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    position: "relative",
  },
  avatarImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  editBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#8B6F47",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: "white",
  },
  avatarEditText: {
    fontSize: 16,
    color: "white",
    fontWeight: "700",
  },
  settingSection: {
    backgroundColor: "#F5F8E8",
    borderRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 24,
    marginBottom: 20,
  },
  sectionTitle: {
    marginBottom: 16,
  },
  sectionTitleText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#8B6F47",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  settingItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 0,
    backgroundColor: "transparent",
    borderBottomWidth: 0,
    marginBottom: 12,
  },
  settingItemLabel: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  settingLabelContainer: {
    marginLeft: 12,
    flex: 1,
  },
  settingLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#8B6F47",
  },
  settingValue: {
    fontSize: 13,
    color: "#8B6F47",
    marginTop: 4,
    fontWeight: "500",
  },
  settingItemLogout: {
    marginBottom: 12,
  },
  settingItemDanger: {
    borderBottomWidth: 0,
    borderRadius: 8,
    marginBottom: 0,
    marginTop: 4,
    paddingVertical: 12,
  },
});
