import { StyleSheet } from "react-native";
import { FONT_FAMILY } from "@/config/fontConfig";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    paddingTop: 10,
    paddingBottom: 40,
    paddingHorizontal: 18,
  },
  backTitle: {
    paddingTop: 8,
    fontFamily: FONT_FAMILY.medium,
  },
  photoCard: {
    marginTop: 18,
    alignSelf: "center",
    width: "100%",
    maxWidth: 320,
    aspectRatio: 1.15,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#B9A37A",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  leafBackground: {
    position: "absolute",
    width: "100%",
    height: "100%",
  },
  photoFrame: {
    width: "72%",
    height: "72%",
    borderRadius: 18,
    backgroundColor: "hsla(0, 0%, 100%, 0.00)",
    borderWidth: 1,
    borderColor: "#F2E4CC",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
    transform: [{ translateX: -6 }, { translateY: -20 }],
  },
  photo: {
    width: "100%",
    height: "100%",
  },
  leafPhotoWrapper: {
    width: "100%",
    height: "100%",
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
  },
  leafPhoto: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  zoomButton: {
    position: "absolute",
    right: 12,
    bottom: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    borderWidth: 0.5,
    borderColor: "#D7B88E",
    alignItems: "center",
    justifyContent: "center",
    transform: [{ translateX: -22 }, { translateY: -40 }],
  },
  detailBorder: {
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  detailBorderImage: {
    borderRadius: 18,
  },
  detailCard: {
    backgroundColor: "#F9EBD3",
    alignSelf: "center",
    width: "94%",
    maxWidth: 320,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginBottom: 9,
    transform: [{ translateX: 5 }, { translateY: 0 }],
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#D7B88E",
    borderStyle: "dashed",
  },
  iconBadge: {
    width: 26,
    height: 26,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  iconImage: {
    width: 18,
    height: 18,
    resizeMode: "contain",
  },
  detailText: {
    marginLeft: 10,
    fontSize: 16,
    color: "#7A4B2A",
    fontWeight: "600",
    fontFamily: FONT_FAMILY.medium,
  },
  dashLine: {
    flex: 1,
    marginLeft: 10,
    height: 1,
    borderBottomWidth: 1,
    borderBottomColor: "#B79066",
    borderStyle: "dashed",
  },
  addTagButton: {
    marginLeft: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#B79066",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF7EA",
  },
  memoRow: {
    marginTop: 8,
    backgroundColor: "#FFF8EC",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D7B88E",
    paddingHorizontal: 12,
    paddingVertical: 12,
    minHeight: 44,
    position: "relative",
  },
  memoText: {
    fontSize: 15,
    color: "#7A4B2A",
    lineHeight: 20,
    fontFamily: FONT_FAMILY.regular,
  },
  memoInput: {
    fontSize: 15,
    color: "#7A4B2A",
    lineHeight: 20,
    minHeight: 32,
    paddingRight: 34,
    fontFamily: FONT_FAMILY.regular,
  },
  memoIconButton: {
    position: "absolute",
    right: 10,
    bottom: 10,
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 0.1,
    borderColor: "#D7B88E",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF7EA",
  },
  zoomOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  zoomImage: {
    width: "92%",
    height: "72%",
  },
  zoomClose: {
    position: "absolute",
    top: 60,
    right: 24,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.15)",
  },
});
