import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#E3CBA5",
    shadowColor: "#B89B68",
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  fieldRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#D5B78E",
    borderStyle: "dashed",
  },
  fieldRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 6,
    alignItems: "flex-start",
  },
  iconBadge: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  iconImage: {
    width: 20,
    height: 20,
    resizeMode: "contain",
  },
  fieldContent: {
    flex: 1,
    marginHorizontal: 10,
  },
  fieldPlaceholder: {
    fontSize: 16,
    color: "#B5906E",
    letterSpacing: 0.5,
  },
  fieldInput: {
    flex: 1,
    marginHorizontal: 10,
    fontSize: 16,
    color: "#7A4B2A",
    paddingVertical: 2,
    backgroundColor: "transparent",
  },
  memoField: {
    flex: 1,
    width: "100%",
    position: "relative",
    marginHorizontal: 10,
  },
  memoInput: {
    minHeight: 80,
    borderWidth: 1,
    borderColor: "#D5B78E",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 6,
    paddingRight: 36,
    marginHorizontal: 0,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
  },
  memoIconButton: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
  },
  actionButton: {
    width: 28,
    height: 28,
    borderRadius: 9,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
});
